= wordpress_intro

New challenge...

Getting started, I check some info on https://wordpress.com/nl/

- [x] register
- [x]  "start your website"
- [x] free option domain name for your website: deliciousrecepies587404528 (start with a free site)

=> I have my first site :-)


I don't think this is very user-friendly
I have to read more to understand all this...

## pages created
 - contact file
 - some info and foto's


But how do I connect them al? I connected a button with a recipe page, but I don't understand how to fix the homepage?







The plus button in the toolbar opens up the block inserter, this is to add new elements to your page.
If you want a nice overview of all elements on your page, click on the list view in the toolbar
To the right of the toolbar, you can open up the settings. These show you the settings of the page you're on or the block you select.
Next to the settings you can change the fonts and global styles
The button with the 3 dots is the option button. Right now you can see we are in the visual editor, but if you want to write code you can also open the code editor.
Let's add some things! Open up the block inserter
You can see a lot of categories, each containing elements you can add to your page
From each category, pick at least 1 of the blocks to add to this page, or any other page you make. (Except for the earn category)
If you can't find one in the category that does not require a premium account, skip the category.
Make sure to customise every block, you can use dummy / fake text but don't leave anything empty that shouldn't be.
Let's get hacky! Open up the code editor
In the code, add a div and put some text in it at the top.
Above that, add a style tag and customise the div to have a background color.
Wordpress doesn't like you doing that, so some wonky stuff might happen
There is a way to overcome this, the end result will be your div with a background color
Let's customise our theme! Go back to the home view of your website and click on "appearance" in the left toolbar
Now we can customise our selected theme or change it! Go ahead and click on "customise"
In here we can change stuff like colors, menus and so on.
Adding additional css is a premium feature, however in the previous step we have learned to overcome this with our developer knowledge! Nice try Wordpress!
Wordpress does their best though to make our life a living hell when we try to change something through css, so not everything will work.
Remember how to customise your fonts? Go ahead and pick one to your liking, don't leave it at the default font!
Last step, add a contact form anywhere on your pages.